name: property_checker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/prop_checker_logo.jpg

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/prop_checker_logo.jpg
  color: "#FFFFFF"
  android_12:
    image: assets/prop_checker_logo.jpg
    color: "#FFFFFF"
